name: Build
on:
  [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK
      uses: actions/setup-java@v5
      with:
        java-version: 21
        distribution: 'temurin' # Eclipse JDK
        server-id: github
        settings-path: ${{ github.workspace }}
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        gradle-version: 'current'
    - name: Setup Ghidra
      uses: er28-0652/setup-ghidra@master
      with:
        version: 11.4.2
    - name: Build
      working-directory: SnesLoader
      run: "gradle"
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ghidra-snes-loader
        path: |
          SnesLoader/dist/*.zip
