name: Build
on:
  [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK
      uses: actions/setup-java@v5
      with:
        java-version: 17
        distribution: 'temurin' # Eclipse JDK
        server-id: github
        settings-path: ${{ github.workspace }}
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        gradle-version: 'current'
    - name: Setup Ghidra
      uses: er28-0652/setup-ghidra@master
      with:
        version: 11.4
    - name: Build
      run: "gradle"
    - name: Release
      uses: shogo82148/actions-upload-release-asset@v1
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: "dist/ghidra_*_SNESloader.zip"
